--- LICH SU GIAO DICH --- 
--1080: Last payment charge (LPC)
--1090: INTEREST/INCOME
--3240: CARD DOWNGRADE FEE
SELECT distinct A.*,F9_IR134_CURR_DPD,NVL(FX_OA008_TXN_TYP,FX_IB006_TXN_TYP) TXN_TYP_CODE
FROM
(
SELECT F9_IRC_CRE_TMS,F9_IRC_LOC_ACCT LOC,FX_IRC_CRD_BRN,PX_IRC_OWN_PAN,F9_IRC_TXN_DT TRANSACTION_DATE, 
P9_IRC_PST_DT POSTING_DATE,FX_IRC_TXN_DESC DESCRIPTION,F9_IRC_SETL_AMT AMOUNT, FX_IRC_APV_CDE,
F9_IRC_TXN_CDE TXN_CODE,F9_IRC_TXN_CRNCY_CDE CURNCY_CODE,F9_IRC_TXN_AMT TXN_AMT_ORIGN,F9_IRC_AMT_LCL_CRNCY LCL_CRNCY,
F9_IRC_COMM_CHRG COMM_CHRG,P9_IRC_SEQ_NO SEQ_NO,F9_IRC_MCC,F9_IRC_TXN_TYP,FX_IRC_CRD_PGM,FX_IRC_CRD_PRD
FROM IRC02_HIST@IM
WHERE FX_IRC_CRD_BRN='MC' AND F9_IRC_LOC_ACCT LIKE '8%'
UNION ALL
SELECT F9_IRC_CRE_TMS,F9_IRC_LOC_ACCT LOC,FX_IRC_CRD_BRN,PX_IRC_OWN_PAN,F9_IRC_TXN_DT TRANSACTION_DATE, 
P9_IRC_PST_DT POSTING_DATE,FX_IRC_TXN_DESC DESCRIPTION,F9_IRC_SETL_AMT AMOUNT, FX_IRC_APV_CDE,
F9_IRC_TXN_CDE TXN_CODE,F9_IRC_TXN_CRNCY_CDE CURNCY_CODE,F9_IRC_TXN_AMT TXN_AMT_ORIGN,F9_IRC_AMT_LCL_CRNCY LCL_CRNCY,
F9_IRC_COMM_CHRG COMM_CHRG,P9_IRC_SEQ_NO SEQ_NO,F9_IRC_MCC,F9_IRC_TXN_TYP,FX_IRC_CRD_PGM,FX_IRC_CRD_PRD
FROM IRC02@IM
WHERE FX_IRC_CRD_BRN='MC' AND F9_IRC_LOC_ACCT LIKE '8%'
) A
INNER JOIN IR134@IM ON A.LOC=P9_IR134_LOC_ACCT
LEFT JOIN OA008@AM ON PX_OA008_PAN=PX_IRC_OWN_PAN AND FX_OA008_APV_CDE=FX_IRC_APV_CDE AND F9_OA008_DT=POSTING_DATE
LEFT JOIN IB006@IM ON PX_IB006_PAN=PX_IRC_OWN_PAN AND PX_IB006_APV_CDE=FX_IRC_APV_CDE AND F9_IB006_DT=POSTING_DATE
WHERE POSTING_DATE BETWEEN 20200825 AND 20210222
AND TXN_CODE=3240
ORDER BY LOC,POSTING_DATE

/--- DATA IR134 ---
SELECT * FROM IR134@IM
WHERE FX_IR134_CRD_BRN='MC'
AND F9_IR134_ACCT_PROV=8
--AND FX_IR134_PRD_CLS='W'
ORDER BY F9_IR134_UPD_TMS DESC

/--- Trang thai the --- 
SELECT B.F9_IR025_LOC_ACCT,B.F9_IR025_EXPI_DT EXPI_DT,F9_IR025_CRD_ATV_DT CRD_ATV_DT,FX_IR025_CRD_ATV_UID CRD_ATV_UID,
F9_IR025_CNCL_DT CNCL_DT,FX_IR025_CLS CARD_STATUS,F9_IR025_ISSUE_DT ISSUE_DT
FROM IR025@IM B 
WHERE F9_IR025_LOC_ACCT LIKE '8%'

/--- DS CR AMOUNT, AGE CODE/DPD, MIA BY LOC---
SELECT P9_IR134_LOC_ACCT,P9_IR134_LOC_ACCT,
FX_IR134_CRD_BRN,F9_IR134_MERC_CR_ADJ+F9_IR134_INTRL_CR_ADJ+F9_IR134_CSH_PMT+F9_IR134_CHQ_PMT CR_AMT,
FX_IR134_CURR_AGE_CDE,F9_IR134_CURR_DPD,FX_IR134_MIA,FX_IR134_AUTO_DB_OPT,FX_IR134_CASA
FROM IR134@IM
WHERE P9_IR134_LOC_ACCT LIKE '8%'

/--- LIMIT ONHOLD ---
SELECT  P9_IR134_LOC_ACCT,FX_IR134_CURR_AGE_CDE,F9_IR134_CURR_DPD,FX_IR134_MIA,FX_IR134_AUTO_DB_OPT,
F9_IR134_ACCR_CSH_INT, F9_IR134_ACCR_RTL_INT, F9_OA001_APV,F9_IR835_AMT_HLD,F9_OA001_CLS_BAL
FROM IR134@IM
LEFT JOIN OA001@AM ON P9_OA001_ACCT_NUM=P9_IR134_LOC_ACCT
LEFT JOIN IR835@IM ON P9_IR835_ACCT_NUM=P9_IR134_LOC_ACCT
WHERE P9_IR134_LOC_ACCT LIKE '8%'

/--- BIL_NUMN_CSH IR134---
SELECT P9_IR134_LOC_ACCT,F9_IR134_BIL_NUMN_CSH_0 ,F9_IR134_BIL_NUMN_CSH_1,F9_IR134_BIL_NUMN_CSH_2 
FROM IR134@IM
WHERE P9_IR134_LOC_ACCT LIKE '8%'
AND FX_IR134_CRD_BRN='MC'

/--- Replace card ---
SELECT   F9_IR635_REQ_DT,B.F9_IRPANMAP_LOC,DED2@IM(FX_IR635_PRIN_PAN,'A') OLD_CRD,D.F9_DW005_ANV_DT,D.F9_DW005_EXPI_DT EXPI_DT_OLD_CARD,
DED2@IM(FX_IR635_NEW_PAN,'A') NEW_CRD,E.F9_DW005_EXPI_DT EXPI_DT_NEW_CARD,
FX_IR635_CRD_PGM,FX_IR635_NEW_CRD_PGM,FX_IR635_CRD_BRN,PX_IR515_CB_ACCT_NUM
FROM   ir635@IM A
LEFT JOIN IR_PAN_MAP@IM B ON A.FX_IR635_PRIN_PAN=B.PX_IRPANMAP_PAN 
LEFT JOIN IR515@IM C ON C.P9_IR515_PRO_NO=F9_IR635_PRO_NO
LEFT JOIN DW005 D ON FX_IR635_PRIN_PAN=D.PX_DW005_PAN
LEFT JOIN DW005 E ON FX_IR635_NEW_PAN=E.PX_DW005_PAN
WHERE   fx_ir635_new_crd_pgm IN ('MDTC4')
    AND TRIM (fx_ir635_crd_pgm) <> TRIM (fx_ir635_new_crd_pgm)
    AND F9_IR635_REQ_DT>=20190601
ORDER BY   f9_ir635_cre_tms ASC


/--- TXN IPP PAYMENT (cham sao ke)---
SELECT TXN_CRE_TMS,TXN_DT,TXN_TM,TXN_STMT_MNTH,TXN_CRD_BRN,TXN_APV_CDE,TXN_LOC,TXN_CDE,TXN_DESC,TXN_AMT,FX_IR025_CRD_PGM CRD_PGM, FX_IR025_CRD_PRD CRD_PRD
FROM ipp_transactions@dw
LEFT JOIN IR025@IM ON TXN_LOC=F9_IR025_LOC_ACCT
WHERE TXN_DT BETWEEN 20210126 AND 20210205
AND TXN_CRD_BRN='MC'
AND FX_IR025_CRD_PRD<>'W'
AND TXN_AMT<0
ORDER BY TXN_LOC,TXN_CRE_TMS ASC

/--- TXN THONG THUONG PAYMENT (cham sao ke)---
SELECT distinct A.*--,F9_IR134_CURR_DPD,NVL(FX_OA008_TXN_TYP,FX_IB006_TXN_TYP) TXN_TYP_CODE
FROM
(
SELECT F9_IRC_CRE_TMS,F9_IRC_LOC_ACCT LOC,FX_IRC_CRD_BRN,PX_IRC_OWN_PAN, F9_IRC_TXN_DT TRANSACTION_DATE, P9_IRC_PST_DT POSTING_DATE,FX_IRC_TXN_DESC DESCRIPTION,
F9_IRC_SETL_AMT AMOUNT, FX_IRC_APV_CDE,F9_IRC_TXN_CDE TXN_CODE,
F9_IRC_TXN_CRNCY_CDE CURNCY_CODE,F9_IRC_TXN_AMT TXN_AMT_ORIGN,F9_IRC_AMT_LCL_CRNCY LCL_CRNCY,F9_IRC_COMM_CHRG COMM_CHRG,P9_IRC_SEQ_NO SEQ_NO,
F9_IRC_MCC,F9_IRC_TXN_TYP,FX_IRC_CRD_PGM,FX_IRC_CRD_PRD
FROM IRC02_HIST@IM
WHERE FX_IRC_CRD_BRN='MC' AND F9_IRC_LOC_ACCT LIKE '8%'
UNION ALL
SELECT F9_IRC_CRE_TMS,F9_IRC_LOC_ACCT LOC,FX_IRC_CRD_BRN,PX_IRC_OWN_PAN,F9_IRC_TXN_DT TRANSACTION_DATE, P9_IRC_PST_DT POSTING_DATE,FX_IRC_TXN_DESC DESCRIPTION,
F9_IRC_SETL_AMT AMOUNT, FX_IRC_APV_CDE,F9_IRC_TXN_CDE TXN_CODE,
F9_IRC_TXN_CRNCY_CDE CURNCY_CODE,F9_IRC_TXN_AMT TXN_AMT_ORIGN,F9_IRC_AMT_LCL_CRNCY LCL_CRNCY,F9_IRC_COMM_CHRG COMM_CHRG,P9_IRC_SEQ_NO SEQ_NO,
F9_IRC_MCC,F9_IRC_TXN_TYP,FX_IRC_CRD_PGM,FX_IRC_CRD_PRD
FROM IRC02@IM
WHERE FX_IRC_CRD_BRN='MC' AND F9_IRC_LOC_ACCT LIKE '8%'
) A
INNER JOIN IR134@IM ON A.LOC=P9_IR134_LOC_ACCT
LEFT JOIN OA008@AM ON PX_OA008_PAN=PX_IRC_OWN_PAN AND FX_OA008_APV_CDE=FX_IRC_APV_CDE AND F9_OA008_DT=POSTING_DATE
LEFT JOIN IB006@IM ON PX_IB006_PAN=PX_IRC_OWN_PAN AND PX_IB006_APV_CDE=FX_IRC_APV_CDE AND F9_IB006_DT=POSTING_DATE
WHERE POSTING_DATE BETWEEN 20210126 AND 20210205
AND LCL_CRNCY<0
AND FX_IRC_CRD_PRD<>'W'
ORDER BY LOC,POSTING_DATE

--- Thông số Thẻ ---
-- IR087 , IR172, IR121, IR150, IR269, IR047, IR513, OA115, OA194, OA159, OA160,OA158, OA114


/ --- NAME, CHUC DANH, CIF CBNV SCB


-- Total closing balance MCW
--- Current Closing balance giao dich thuong
SELECT f9_oa001_cls_bal + f9_oa001_apv + f9_oa001_cav_inc 
FROM oa001@AM
WHERE P9_OA001_ACCT_NUM=800000796761

/
--- Current Closing balance IPP
select
sum(finan_mstr_clo_bal)
from ccps.ipp_financial_master a where finan_mstr_loc = 800000796761  and finan_mstr_close_dt = 0
