--------------------------------------------------------
--  File created - Thursday-May-27-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PPT_SENDMAIL
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_SENDMAIL" 
   (	"CASE_ID" VARCHAR2(50 BYTE), 
	"CRE_TMS" NUMBER(17,0), 
	"MAILCONTENT" VARCHAR2(800 BYTE), 
	"MAILTYPE" VARCHAR2(50 BYTE), 
	"MAILTO" VARCHAR2(100 BYTE), 
	"ISSEND" NUMBER(1,0) DEFAULT 0, 
	"MAILTITLE" VARCHAR2(150 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 524288 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0)
  TABLESPACE "DWT02" ;

   COMMENT ON TABLE "FPT"."PPT_SENDMAIL"  IS 'NOI DUNG EMAIL SE GUI';
--------------------------------------------------------
--  DDL for Table PPT_SYS_GROUP
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_SYS_GROUP" 
   (	"ID" NUMBER, 
	"GROUP_NAME" VARCHAR2(100 BYTE), 
	"GROUP_DESC" VARCHAR2(255 BYTE), 
	"CRE_TMS" NUMBER(17,0), 
	"UPD_TMS" NUMBER(17,0), 
	"GROUP_TYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Table PPT_SYS_USER
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_SYS_USER" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"FULLNAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"DESCT" VARCHAR2(70 BYTE), 
	"CRE_TMS" NUMBER(17,0), 
	"UPD_TMS" NUMBER(17,0), 
	"IS_LOCK" NUMBER(1,0) DEFAULT 0, 
	"USR_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Table PPT_SYS_VIEW
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_SYS_VIEW" 
   (	"ID" NUMBER, 
	"VIEWNAME" VARCHAR2(50 BYTE), 
	"VIEWDESC" VARCHAR2(50 BYTE), 
	"PARENT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Table PPT_SENTMAIL
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_SENTMAIL" 
   (	"ID" NUMBER, 
	"CASE_ID" VARCHAR2(50 BYTE), 
	"MAILTYPE" VARCHAR2(14 BYTE), 
	"MAILCONTENT" VARCHAR2(600 BYTE), 
	"CRE_TMS" NUMBER(17,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" ;

   COMMENT ON COLUMN "FPT"."PPT_SENTMAIL"."CASE_ID" IS 'CASE ID';
   COMMENT ON COLUMN "FPT"."PPT_SENTMAIL"."MAILTYPE" IS 'NEW; DECLINED; CANCELED; ROUTEBACK;REMIND';
   COMMENT ON TABLE "FPT"."PPT_SENTMAIL"  IS 'bang luu thong tin cac case da gui mail theo tung loai tinh trang cua case';
--------------------------------------------------------
--  DDL for Table PPT_SYS_USR_BRANCH
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_SYS_USR_BRANCH" 
   (	"USERNAME" VARCHAR2(50 BYTE), 
	"BRANCH_CODE" CHAR(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Table PPT_CRD_PGM
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_CRD_PGM" 
   (	"FX_IR121_CRD_BRN" CHAR(2 BYTE), 
	"PX_IR121_CRD_PGM" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Table PPT_HIBERNATE_SEQUENCES
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_HIBERNATE_SEQUENCES" 
   (	"SEQUENCE_NAME" VARCHAR2(50 BYTE), 
	"SEQUENCE_NEXT_HI_VALUE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Table PPT_SYS_PERMISSION
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_SYS_PERMISSION" 
   (	"ID" NUMBER, 
	"USERID" NUMBER, 
	"VIEWID" VARCHAR2(50 BYTE), 
	"ISDELETE" NUMBER(1,0) DEFAULT 0, 
	"ISEDIT" NUMBER(1,0) DEFAULT 0, 
	"ISVIEW" NUMBER(1,0) DEFAULT 0, 
	"ISCHEKER" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Table PPT_CRD_DETAIL
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_CRD_DETAIL" 
   (	"ID" NUMBER, 
	"CIF_NO" VARCHAR2(100 BYTE), 
	"CRD_PRIN_SUPP" VARCHAR2(1 BYTE), 
	"CRD_TYPE" VARCHAR2(10 BYTE), 
	"CUST_NAME" VARCHAR2(100 BYTE), 
	"FW_BRN_CDE" VARCHAR2(3 BYTE), 
	"ISSUE_DATE" VARCHAR2(8 BYTE), 
	"ISSUE_TYPE" VARCHAR2(15 BYTE), 
	"PAN" VARCHAR2(20 BYTE), 
	"BRCH_CDE" CHAR(3 BYTE), 
	"REC_MK" NUMBER(1,0) DEFAULT 0, 
	"REC_MK_DATE" VARCHAR2(17 BYTE), 
	"REC_MK_ISCHECK" NUMBER(1,0) DEFAULT 0, 
	"REC_MK_LOCK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_BRANCH" NUMBER(1,0) DEFAULT 0, 
	"TRANS_BRANCH_DATE" VARCHAR2(17 BYTE), 
	"TRANS_BRANCH_EMP_CODE" VARCHAR2(6 BYTE), 
	"TRANS_BRANCH_EMP_NAME" VARCHAR2(50 BYTE), 
	"TRANS_BRANCH_ISCHECK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_BRANCH_LOCK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_BRANCH_NOTE" VARCHAR2(250 BYTE), 
	"TRANS_CUST" NUMBER(1,0), 
	"TRANS_CUST_DATE" VARCHAR2(17 BYTE), 
	"TRANS_CUST_ISCHECK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_CUST_LOCK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_EMP" NUMBER(1,0) DEFAULT 0, 
	"TRANS_EMP_CODE" VARCHAR2(6 BYTE), 
	"TRANS_EMP_DATE" VARCHAR2(17 BYTE), 
	"TRANS_EMP_ISCHECK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_EMP_LOCK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_EMP_NAME" VARCHAR2(50 BYTE), 
	"TRANS_EMP_NOTE" VARCHAR2(250 BYTE), 
	"TRANS_MK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_MK_DATE" VARCHAR2(17 BYTE), 
	"TRANS_MK_ISCHECK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_MK_LOCK" NUMBER(1,0) DEFAULT 0, 
	"FILE_PIN" VARCHAR2(50 BYTE), 
	"TRANS_BRANCH_REC" NUMBER(1,0) DEFAULT 0, 
	"TRANS_BRANCH_REC_DATE" VARCHAR2(17 BYTE), 
	"TRANS_BRANCH_REC_LOCK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_BRANCH_REC_CHECK" NUMBER(1,0) DEFAULT 0, 
	"TRANS_EMP_RENDER" VARCHAR2(200 BYTE), 
	"TRANS_EMP_RENDER1" VARCHAR2(200 BYTE), 
	"TRANS_EMP_RENDER2" VARCHAR2(200 BYTE), 
	"TRANS_EMP_RENDER_DATE" VARCHAR2(17 BYTE), 
	"TRANS_EMP_RENDER_DATE1" VARCHAR2(17 BYTE), 
	"TRANS_EMP_RENDER_DATE2" VARCHAR2(17 BYTE), 
	"TRANS_EMP_DATE1" VARCHAR2(17 BYTE), 
	"TRANS_EMP_DATE2" VARCHAR2(17 BYTE), 
	"TRANS_EMP_LOCK1" NUMBER(1,0), 
	"TRANS_EMP_LOCK2" NUMBER(1,0), 
	"TRANS_EMP_LOCK3" NUMBER(1,0), 
	"TRANS_EMP_ISCHECK1" NUMBER(1,0), 
	"TRANS_EMP_ISCHECK2" NUMBER(1,0), 
	"TRANS_EMP_ISCHECK3" NUMBER(1,0), 
	"TRANS_EMP_ISRENDER" NUMBER(1,0), 
	"TRANS_EMP_ISRENDER1" NUMBER(1,0), 
	"TRANS_EMP_ISRENDER2" NUMBER(1,0), 
	"TRANS_EMP_LOCK4" NUMBER(1,0), 
	"TRANS_EMP_ISCHECK4" NUMBER(1,0), 
	"TRANS_MK_REAL_TIME_LOCK" NUMBER(17,0), 
	"TRANS_MK_REAL_TIME_CHECK" NUMBER(17,0), 
	"TRANS_BRN_REC_REAL_TIME_LOCK" NUMBER(17,0), 
	"TRANS_BRN_REC_REAL_TIME_CHECK" NUMBER(17,0), 
	"TRANS_CUST_REAL_TIME_LOCK" NUMBER(17,0), 
	"TRANS_CUST_REAL_TIME_CHECK" NUMBER(17,0), 
	"TRANS_CUST_STATUS" VARCHAR2(2 BYTE), 
	"TRANS_CUST_NOTE" VARCHAR2(100 BYTE), 
	"SALEOFFICER_CODE" VARCHAR2(10 BYTE), 
	"SALEOFFICER_CODE_NAME" VARCHAR2(100 BYTE), 
	"GTTN" NUMBER(1,0) DEFAULT 0, 
	"XACNHAN_GTTN" NUMBER(1,0) DEFAULT 0, 
	"TIME_XACNHAN_GTTN" NUMBER(17,0), 
	"TIME_GTTN" NUMBER(17,0), 
	"DELIV_BY_BRCH" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Table PPT_EMB_CARD_DETAIL
--------------------------------------------------------

  CREATE TABLE "FPT"."PPT_EMB_CARD_DETAIL" 
   (	"CRN" NUMBER(9,0), 
	"CIF" VARCHAR2(19 BYTE), 
	"CUST_NAME" VARCHAR2(120 BYTE), 
	"LOC" NUMBER, 
	"PAN" CHAR(19 BYTE), 
	"PANMASK" VARCHAR2(46 BYTE), 
	"CRD_PGM" VARCHAR2(24 BYTE), 
	"PRIN_SUPP" VARCHAR2(4 BYTE), 
	"CRD_CAT" VARCHAR2(12 BYTE), 
	"EMB_DT" NUMBER(8,0), 
	"BRCH_CDE" VARCHAR2(12 BYTE), 
	"REL_FORM" VARCHAR2(4 BYTE), 
	"CRD_BRN" VARCHAR2(2 BYTE), 
	"SLS_OFC_CDE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" ;
--------------------------------------------------------
--  DDL for Index PK_PPT_SENDMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPT"."PK_PPT_SENDMAIL" ON "FPT"."PPT_SENDMAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index PK_PPT_SYS_GROUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPT"."PK_PPT_SYS_GROUP" ON "FPT"."PPT_SYS_GROUP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index PK_PPT_SYS_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPT"."PK_PPT_SYS_USER" ON "FPT"."PPT_SYS_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index PK_PPT_SYS_VIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPT"."PK_PPT_SYS_VIEW" ON "FPT"."PPT_SYS_VIEW" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index PK_PPT_SENTMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPT"."PK_PPT_SENTMAIL" ON "FPT"."PPT_SENTMAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index IDX$$_001F0001
--------------------------------------------------------

  CREATE INDEX "FPT"."IDX$$_001F0001" ON "FPT"."PPT_SYS_USR_BRANCH" ("USERNAME", TRIM("BRANCH_CODE")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPT" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index PK_PPT_SYS_USR_BRANCH
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPT"."PK_PPT_SYS_USR_BRANCH" ON "FPT"."PPT_SYS_USR_BRANCH" ("USERNAME", "BRANCH_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index PK_PPT_SYS_PERMISSION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPT"."PK_PPT_SYS_PERMISSION" ON "FPT"."PPT_SYS_PERMISSION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index IDX$$_001F0004
--------------------------------------------------------

  CREATE INDEX "FPT"."IDX$$_001F0004" ON "FPT"."PPT_CRD_DETAIL" ("CIF_NO", "CRD_PRIN_SUPP", "PAN", "ISSUE_TYPE", TO_NUMBER("ISSUE_DATE")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPT" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index PK_PPT_CRD_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPT"."PK_PPT_CRD_DETAIL" ON "FPT"."PPT_CRD_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02" 
  PARALLEL 4 ;
--------------------------------------------------------
--  Constraints for Table PPT_SENDMAIL
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_SENDMAIL" MODIFY ("CASE_ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENDMAIL" MODIFY ("CRE_TMS" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENDMAIL" MODIFY ("MAILCONTENT" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENDMAIL" MODIFY ("MAILTYPE" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENDMAIL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENDMAIL" ADD CONSTRAINT "PK_PPT_SENDMAIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPT_SYS_GROUP
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_SYS_GROUP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_GROUP" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_GROUP" MODIFY ("GROUP_DESC" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_GROUP" MODIFY ("CRE_TMS" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_GROUP" ADD CONSTRAINT "PK_PPT_SYS_GROUP" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPT_SYS_USER
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_SYS_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_USER" MODIFY ("CRE_TMS" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_USER" MODIFY ("IS_LOCK" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_USER" ADD CONSTRAINT "PK_PPT_SYS_USER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPT_SYS_VIEW
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_SYS_VIEW" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_VIEW" ADD CONSTRAINT "PK_PPT_SYS_VIEW" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPT_SENTMAIL
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_SENTMAIL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENTMAIL" MODIFY ("CASE_ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENTMAIL" MODIFY ("MAILTYPE" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENTMAIL" MODIFY ("CRE_TMS" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SENTMAIL" ADD CONSTRAINT "PK_PPT_SENTMAIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPT_SYS_USR_BRANCH
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_SYS_USR_BRANCH" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_USR_BRANCH" MODIFY ("BRANCH_CODE" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_USR_BRANCH" ADD CONSTRAINT "PK_PPT_SYS_USR_BRANCH" PRIMARY KEY ("USERNAME", "BRANCH_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPT_CRD_PGM
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_CRD_PGM" MODIFY ("FX_IR121_CRD_BRN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PPT_HIBERNATE_SEQUENCES
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_HIBERNATE_SEQUENCES" MODIFY ("SEQUENCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_HIBERNATE_SEQUENCES" MODIFY ("SEQUENCE_NEXT_HI_VALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PPT_SYS_PERMISSION
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_SYS_PERMISSION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_PERMISSION" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_PERMISSION" MODIFY ("ISDELETE" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_PERMISSION" MODIFY ("ISEDIT" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_PERMISSION" MODIFY ("ISVIEW" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_PERMISSION" MODIFY ("ISCHEKER" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_SYS_PERMISSION" ADD CONSTRAINT "PK_PPT_SYS_PERMISSION" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "DWT02"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPT_CRD_DETAIL
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_CRD_DETAIL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_CRD_DETAIL" ADD CONSTRAINT "PK_PPT_CRD_DETAIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWT02"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPT_EMB_CARD_DETAIL
--------------------------------------------------------

  ALTER TABLE "FPT"."PPT_EMB_CARD_DETAIL" MODIFY ("PAN" NOT NULL ENABLE);
  ALTER TABLE "FPT"."PPT_EMB_CARD_DETAIL" MODIFY ("EMB_DT" NOT NULL ENABLE);
