REM INSERTING into FPT.PPT_HIBERNATE_SEQUENCES
SET DEFINE OFF;
Insert into FPT.PPT_HIBERNATE_SEQUENCES (SEQUENCE_NAME,SEQUENCE_NEXT_HI_VALUE) values ('ppt_crd_detail',256228);
Insert into FPT.PPT_HIBERNATE_SEQUENCES (SEQUENCE_NAME,SEQUENCE_NEXT_HI_VALUE) values ('cwst_sys_user',2533);
Insert into FPT.PPT_HIBERNATE_SEQUENCES (SEQUENCE_NAME,SEQUENCE_NEXT_HI_VALUE) values ('cwst_sys_permission  ',34);
Insert into FPT.PPT_HIBERNATE_SEQUENCES (SEQUENCE_NAME,SEQUENCE_NEXT_HI_VALUE) values ('cwst_case_detail_hist',182424);
Insert into FPT.PPT_HIBERNATE_SEQUENCES (SEQUENCE_NAME,SEQUENCE_NEXT_HI_VALUE) values ('cwst_sendmail',108586);
Insert into FPT.PPT_HIBERNATE_SEQUENCES (SEQUENCE_NAME,SEQUENCE_NEXT_HI_VALUE) values ('cwst_sentmail',79);
Insert into FPT.PPT_HIBERNATE_SEQUENCES (SEQUENCE_NAME,SEQUENCE_NEXT_HI_VALUE) values ('cwst_crd_detail',2);
