--------------------------------------------------------
--  DDL for Procedure FDS_GD_HIT_RULE_NHOM_1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CCPS"."FDS_GD_HIT_RULE_NHOM_1" (
    P_FROMDATE IN NUMBER,
    P_TODATE   IN NUMBER,
    sys_cursor OUT SYS_REFCURSOR
) Is


Begin
OPEN sys_cursor FOR


SELECT CASE_NO CASE,RULE, CRE_TMS THOI_GIAN,CARD_NO SO_THE, CARD_TYPE || CARD_TYPE_SUPP LOAI_THE, 
F9_DW005_LOC_ACCT || F9_DW006_LOC_ACCT LOC, CIF_NO CIF , FX_DW005_BRCH_CDE || FX_DW006_BRCH_CDE DVPHT, FX_IR124_BRCH_NAME || FX_IR124_BRCH_NAME_SUPP TEN_DVPHT
FROM (
SELECT B.CRE_TMS,B.CASE_NO,SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),1,6) || 'XXXXXX' || SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),13,16) CARD_NO
,CASE WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE
,CASE WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE_SUPP
, F9_DW005_LOC_ACCT, F9_DW006_LOC_ACCT,CIF_NO, (SELECT LISTAGG(RULE_ID, ',') WITHIN GROUP (ORDER BY CASE_NO) FROM fds_case_hit_rules WHERE CASE_NO = B.CASE_NO) RULE
,FX_DW005_BRCH_CDE,FX_DW006_BRCH_CDE, D.FX_IR124_BRCH_NAME,F.FX_IR124_BRCH_NAME FX_IR124_BRCH_NAME_SUPP
FROM FDS_CASE_STATUS A INNER JOIN FDS_CASE_DETAIL B ON A.CASE_NO = B.CASE_NO
LEFT JOIN DW005 C ON PX_DW005_PAN = B.ENC_CRD_NO
LEFT JOIN DW006 E ON PX_DW006_OWN_PAN = ENC_CRD_NO
LEFT JOIN IR124@IM D ON FX_DW005_BRCH_CDE = D.PX_IR124_BRCH_CDE
LEFT JOIN IR124@IM F ON FX_DW006_BRCH_CDE = F.PX_IR124_BRCH_CDE
WHERE A.CLOSED_REASON IN ('CCE','CRC')  AND A.CRE_TMS between P_FROMDATE and  P_TODATE

UNION ALL

SELECT C.CRE_TMS,C.CASE_NO,SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),1,6) || 'XXXXXX' || SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),13,16) CARD_NO
,CASE WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE
,CASE WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE_SUPP
, F9_DW005_LOC_ACCT, F9_DW006_LOC_ACCT,CIF_NO, (SELECT LISTAGG(RULE_ID, ',') WITHIN GROUP (ORDER BY CASE_NO) FROM fds_case_hit_rules WHERE CASE_NO = B.CASE_NO) RULE
,FX_DW005_BRCH_CDE,FX_DW006_BRCH_CDE, D.FX_IR124_BRCH_NAME,F.FX_IR124_BRCH_NAME FX_IR124_BRCH_NAME_SUPP
FROM FDS_DESCRIPTION A
LEFT JOIN FDS_CASE_STATUS B ON B.CLOSED_REASON = A.TYPE AND B.OTHER LIKE '%'|| A.ID ||'%'
INNER JOIN FDS_CASE_DETAIL C ON B.CASE_NO = C.CASE_NO
LEFT JOIN DW005 C ON PX_DW005_PAN = ENC_CRD_NO
LEFT JOIN DW006 E ON PX_DW006_OWN_PAN = ENC_CRD_NO
LEFT JOIN IR124@IM D ON FX_DW005_BRCH_CDE = D.PX_IR124_BRCH_CDE
LEFT JOIN IR124@IM F ON FX_DW006_BRCH_CDE = F.PX_IR124_BRCH_CDE
WHERE A.TYPE='CCN' AND B.CRE_TMS between P_FROMDATE and  P_TODATE

UNION ALL

SELECT B.CRE_TMS,B.CASE_NO,SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),1,6) || 'XXXXXX' || SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),13,16) CARD_NO
,CASE WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE
,CASE WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE_SUPP
, F9_DW005_LOC_ACCT, F9_DW006_LOC_ACCT,CIF_NO, (SELECT LISTAGG(RULE_ID, ',') WITHIN GROUP (ORDER BY CASE_NO) FROM fds_case_hit_rules WHERE CASE_NO = B.CASE_NO) RULE
,FX_DW005_BRCH_CDE,FX_DW006_BRCH_CDE, D.FX_IR124_BRCH_NAME,F.FX_IR124_BRCH_NAME FX_IR124_BRCH_NAME_SUPP
FROM FDS_CASE_STATUS A INNER JOIN FDS_CASE_DETAIL B ON A.CASE_NO = B.CASE_NO
LEFT JOIN DW005 C ON PX_DW005_PAN = ENC_CRD_NO
LEFT JOIN DW006 E ON PX_DW006_OWN_PAN = ENC_CRD_NO
LEFT JOIN IR124@IM D ON FX_DW005_BRCH_CDE = D.PX_IR124_BRCH_CDE
LEFT JOIN IR124@IM F ON FX_DW006_BRCH_CDE = F.PX_IR124_BRCH_CDE
WHERE A.CLOSED_REASON = 'CCT' AND A.CRE_TMS between P_FROMDATE and  P_TODATE

UNION ALL

SELECT B.CRE_TMS,B.CASE_NO,SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),1,6) || 'XXXXXX' || SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),13,16) CARD_NO
,CASE WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE
,CASE WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE_SUPP
, F9_DW005_LOC_ACCT, F9_DW006_LOC_ACCT,CIF_NO, (SELECT LISTAGG(RULE_ID, ',') WITHIN GROUP (ORDER BY CASE_NO) FROM fds_case_hit_rules WHERE CASE_NO = B.CASE_NO) RULE
,FX_DW005_BRCH_CDE,FX_DW006_BRCH_CDE, D.FX_IR124_BRCH_NAME,F.FX_IR124_BRCH_NAME FX_IR124_BRCH_NAME_SUPP
FROM FDS_CASE_STATUS A INNER JOIN FDS_CASE_DETAIL B ON A.CASE_NO = B.CASE_NO
LEFT JOIN DW005 C ON PX_DW005_PAN = B.ENC_CRD_NO
LEFT JOIN DW006 E ON PX_DW006_OWN_PAN = ENC_CRD_NO
LEFT JOIN IR124@IM D ON FX_DW005_BRCH_CDE = D.PX_IR124_BRCH_CDE
LEFT JOIN IR124@IM F ON FX_DW006_BRCH_CDE = F.PX_IR124_BRCH_CDE
WHERE A.CLOSED_REASON = 'CNC' AND A.CRE_TMS between P_FROMDATE and  P_TODATE

UNION ALL

SELECT B.CRE_TMS,B.CASE_NO,SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),1,6) || 'XXXXXX' || SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),13,16) CARD_NO
,CASE WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE
,CASE WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE_SUPP
, F9_DW005_LOC_ACCT, F9_DW006_LOC_ACCT,CIF_NO, (SELECT LISTAGG(RULE_ID, ',') WITHIN GROUP (ORDER BY CASE_NO) FROM fds_case_hit_rules WHERE CASE_NO = B.CASE_NO) RULE
,FX_DW005_BRCH_CDE,FX_DW006_BRCH_CDE, D.FX_IR124_BRCH_NAME,F.FX_IR124_BRCH_NAME FX_IR124_BRCH_NAME_SUPP
FROM FDS_CASE_STATUS A INNER JOIN FDS_CASE_DETAIL B ON A.CASE_NO = B.CASE_NO
LEFT JOIN DW005 C ON PX_DW005_PAN = B.ENC_CRD_NO
LEFT JOIN DW006 E ON PX_DW006_OWN_PAN = ENC_CRD_NO
LEFT JOIN IR124@IM D ON FX_DW005_BRCH_CDE = D.PX_IR124_BRCH_CDE
LEFT JOIN IR124@IM F ON FX_DW006_BRCH_CDE = F.PX_IR124_BRCH_CDE
WHERE A.CLOSED_REASON = 'BCC' AND A.CRE_TMS between P_FROMDATE and  P_TODATE

UNION ALL

SELECT B.CRE_TMS,B.CASE_NO,SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),1,6) || 'XXXXXX' || SUBSTR(DED2@IM(ENC_CRD_NO,'FDS'),13,16) CARD_NO
,CASE WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW005_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE
,CASE WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=20 THEN CRD_BRN || ' Debit' WHEN SUBSTR(F9_DW006_LOC_ACCT,1,2)=80 THEN CRD_BRN || ' Credit' END CARD_TYPE_SUPP
, F9_DW005_LOC_ACCT, F9_DW006_LOC_ACCT,CIF_NO, (SELECT LISTAGG(RULE_ID, ',') WITHIN GROUP (ORDER BY CASE_NO) FROM fds_case_hit_rules WHERE CASE_NO = B.CASE_NO) RULE
,FX_DW005_BRCH_CDE,FX_DW006_BRCH_CDE, D.FX_IR124_BRCH_NAME,F.FX_IR124_BRCH_NAME FX_IR124_BRCH_NAME_SUPP
FROM FDS_CASE_STATUS A INNER JOIN FDS_CASE_DETAIL B ON A.CASE_NO = B.CASE_NO
INNER JOIN (
    select min(r.rule_priority) keep(dense_rank first order by r.rule_priority) rule_priority,t.case_no
    from fds_case_hit_rules t 
    join fds_rules r on t.rule_id=r.rule_id 
    GROUP BY t.case_no
    order by t.case_no asc
  ) C ON C.CASE_NO=B.CASE_NO
INNER JOIN fds_rules D ON C.rule_priority=D.rule_priority AND D.RULE_ID IN ('RULE26','RULE21','RULE27','RULE08','RULE28','RULE29','RULE30','RULE22','RULE23','RULE31','RULE03','RULE32','RULE33','RULE10','RULE17','RULE39','RULE40','RULE41','SVIP01','SVIP02')
LEFT JOIN DW005 C ON PX_DW005_PAN = B.ENC_CRD_NO
LEFT JOIN DW006 E ON PX_DW006_OWN_PAN = ENC_CRD_NO
LEFT JOIN IR124@IM D ON FX_DW005_BRCH_CDE = D.PX_IR124_BRCH_CDE
LEFT JOIN IR124@IM F ON FX_DW006_BRCH_CDE = F.PX_IR124_BRCH_CDE
WHERE A.CLOSED_REASON = 'NCR' AND A.CRE_TMS between P_FROMDATE and  P_TODATE

);

End FDS_GD_HIT_RULE_NHOM_1;


/
