--------------------------------------------------------
--  File created - Thursday-May-27-2021   
--------------------------------------------------------
@D:\Users\tanvh1\FN_FDS_RULE03_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE03_V2_1.sql
@D:\Users\tanvh1\FN_FDS_RULE03_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE03_V3_UAT.sql
@D:\Users\tanvh1\FN_FDS_RULE08_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE08_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE10.sql
@D:\Users\tanvh1\FN_FDS_RULE13_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE13_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE13_V3_UAT.sql
@D:\Users\tanvh1\FN_FDS_RULE14.sql
@D:\Users\tanvh1\FN_FDS_RULE14_TEST.sql
@D:\Users\tanvh1\FN_FDS_RULE14_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE14_V3_UAT.sql
@D:\Users\tanvh1\FN_FDS_RULE15.sql
@D:\Users\tanvh1\FN_FDS_RULE15_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE15_V3_UAT.sql
@D:\Users\tanvh1\FN_FDS_RULE16_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE16_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE16_V3_UAT.sql
@D:\Users\tanvh1\FN_FDS_RULE17_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE17_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE19.sql
@D:\Users\tanvh1\FN_FDS_RULE20.sql
@D:\Users\tanvh1\FN_FDS_RULE21_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE21_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE22.sql
@D:\Users\tanvh1\FN_FDS_RULE23_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE23_V2_TEST.sql
@D:\Users\tanvh1\FN_FDS_RULE23_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE26_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE27_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE28.sql
@D:\Users\tanvh1\FN_FDS_RULE29_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE29_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE30_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE30_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE31.sql
@D:\Users\tanvh1\FN_FDS_RULE32.sql
@D:\Users\tanvh1\FN_FDS_RULE33_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE33_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE34.sql
@D:\Users\tanvh1\FN_FDS_RULE34_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE34_V3_UAT.sql
@D:\Users\tanvh1\FN_FDS_RULE35.sql
@D:\Users\tanvh1\FN_FDS_RULE35_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE36.sql
@D:\Users\tanvh1\FN_FDS_RULE37.sql
@D:\Users\tanvh1\FN_FDS_RULE37_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE37_V3_UAT.sql
@D:\Users\tanvh1\FN_FDS_RULE38.sql
@D:\Users\tanvh1\FN_FDS_RULE39.sql
@D:\Users\tanvh1\FN_FDS_RULE39_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE39_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE40.sql
@D:\Users\tanvh1\FN_FDS_RULE41.sql
@D:\Users\tanvh1\FN_FDS_RULE41_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE42.sql
@D:\Users\tanvh1\FN_FDS_RULE42_V2.sql
@D:\Users\tanvh1\FN_FDS_RULE42_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE43.sql
@D:\Users\tanvh1\FN_FDS_RULE43_V3.sql
@D:\Users\tanvh1\FN_FDS_RULE44.sql
@D:\Users\tanvh1\FN_FDS_RULE45.sql
@D:\Users\tanvh1\FN_FDS_SVIP01.sql
@D:\Users\tanvh1\FN_FDS_SVIP01_V2.sql
@D:\Users\tanvh1\FN_FDS_SVIP02.sql
@D:\Users\tanvh1\FN_FDS_SVIP02_V2.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE01.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE02.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE03.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE04.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE05.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE06.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE07.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE09.sql
@D:\Users\tanvh1\FN_FDSPOS_EIB_RULE10.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE01.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE02.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE03.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE04.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE05.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE06.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE07.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE08.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE09.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE10.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE11.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE12.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE13.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE14.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE15.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE16.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE17.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE18.sql
@D:\Users\tanvh1\FN_FDSPOS_V2_RULE19.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE01.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE02.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE03.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE05.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE06.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE07.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE12.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE13.sql
@D:\Users\tanvh1\FN_FDSPOS_V3_RULE19.sql
