--------------------------------------------------------
--  File created - Thursday-May-27-2021   
--------------------------------------------------------
@D:\Users\tanvh1\FDS_GD_HIT_RULE_NHOM_1.sql
@D:\Users\tanvh1\SP_DAILYBACKUP_FDSCARD_DATA.sql
@D:\Users\tanvh1\SP_FDS_CARD_RULES_PROCESS.sql
@D:\Users\tanvh1\SP_FDS_CARD_RULES_PROCESS_BK.sql
@D:\Users\tanvh1\SP_FDS_CARD_RULES_PROCESS_V2.sql
@D:\Users\tanvh1\SP_FDS_MIDVN_RPT.sql
@D:\Users\tanvh1\SP_FDS_PROCESS_S2P.sql
@D:\Users\tanvh1\SP_FDS_RULES_PROCESS_V2.sql
@D:\Users\tanvh1\SP_FDS_RULES_PROCESS_V2_BK_TAN.sql
@D:\Users\tanvh1\SP_FDS_RULES_PROCESS_V3.sql
@D:\Users\tanvh1\SP_FDS_SYN_DATA.sql
@D:\Users\tanvh1\SP_FDS_SYN_DATA_S2P.sql
@D:\Users\tanvh1\SP_FDS_TXNDETAIL_RPT.sql
@D:\Users\tanvh1\SP_FDS_UPDATE_DATA.sql
@D:\Users\tanvh1\SP_FDSPOS_RULES_PROCESS_EIB.sql
@D:\Users\tanvh1\SP_FDSPOS_RULES_PROCESS_V2.sql
@D:\Users\tanvh1\SP_FDSPOS_RULES_PROCESS_V3.sql
@D:\Users\tanvh1\SP_FDSPOS_RULES_PROCESS_VTB.sql
