------------------SUMMARY
SELECT TRANS_TYPE,LOAI_HACH_TOAN,
SUM(COUNT) SL_GD_CHAP_THUAN,
SUM(ST_TRICH_NO) ST_BIDV_TRICH_NO,
SUM(ST_TRICH_NO)+SUM(THU_PHI_INTERCHANGE)-SUM(PHI_INTERCHANGE_PHAI_TRA) ST_GD,
SUM(THU_PHI_INTERCHANGE) THU_PHI_INTERCHANGE,
SUM(PHI_INTERCHANGE_PHAI_TRA) PHI_INTERCHANGE_PHAI_TRA
FROM
(
    SELECT NGAY_ADV,TRANS_TYPE,CARD_BRN,CURR,COUNT,
    CASE WHEN AMOUNT_TYPE='CR' AND REVERSAL='R' THEN -AMOUNT ELSE AMOUNT END ST_TRICH_NO,
    AMOUNT_TYPE,
    CASE WHEN TRANS_TYPE='GDTTHH' OR TRANS_TYPE='GDMSFF' THEN
            (CASE WHEN AMOUNT_TYPE='CR' AND REVERSAL='R' THEN -TRANS_FEE ELSE TRANS_FEE END) 
        ELSE 0 END THU_PHI_INTERCHANGE,
        
    CASE WHEN TRANS_TYPE='GDRTM' OR TRANS_TYPE='GDMSFF' THEN
            (CASE WHEN AMOUNT_TYPE='CR' AND REVERSAL='R' THEN -TRANS_FEE ELSE TRANS_FEE END) 
        ELSE 0 END PHI_INTERCHANGE_PHAI_TRA,
    
    CASE WHEN AMOUNT_TYPE = 'DR' OR (AMOUNT_TYPE='CR' AND REVERSAL='R') THEN 'BAO_NO' ELSE 'BAO_CO' END LOAI_HACH_TOAN,
    CASE WHEN TRANS_TYPE='GDTTHH' THEN 'A' 
        WHEN TRANS_TYPE='GDRTM' THEN 'B' 
        WHEN TRANS_TYPE='GDMSFF' THEN 'C' 
        WHEN TRANS_TYPE='GDNONFI' THEN 'D' 
        WHEN TRANS_TYPE='GDCB' THEN 'E' 
        WHEN TRANS_TYPE='FEECOLL' THEN 'E' END SEQ_NO
    FROM DSQT_HACH_TOAN
    WHERE NGAY_ADV=20200909 AND CURR='VND' AND CARD_BRN='MD' 
    --GROUP BY NGAY_ADV,CURR,CARD_BRN,AMOUNT_TYPE,TRANS_TYPE,REVERSAL
    order by TRANS_TYPE DESC
)
GROUP BY TRANS_TYPE,LOAI_HACH_TOAN,SEQ_NO
ORDER BY SEQ_NO,LOAI_HACH_TOAN DESC


--------------------DETAILS-------
SELECT FILE_NAME,TRANS_TYPE,LOAI_HACH_TOAN,
SUM(COUNT) SL_GD_CHAP_THUAN,
SUM(ST_TRICH_NO) ST_BIDV_TRICH_NO,
SUM(ST_TRICH_NO)+SUM(THU_PHI_INTERCHANGE)-SUM(PHI_INTERCHANGE_PHAI_TRA) ST_GD,
SUM(THU_PHI_INTERCHANGE) THU_PHI_INTERCHANGE,
SUM(PHI_INTERCHANGE_PHAI_TRA) PHI_INTERCHANGE_PHAI_TRA
FROM
(
    SELECT FILE_NAME,NGAY_ADV,TRANS_TYPE,CARD_BRN,CURR,COUNT,
    CASE WHEN AMOUNT_TYPE='CR' AND REVERSAL='R' THEN -AMOUNT ELSE AMOUNT END ST_TRICH_NO,
    AMOUNT_TYPE,
    CASE WHEN TRANS_TYPE='GDTTHH' OR TRANS_TYPE='GDMSFF' THEN
            (CASE WHEN AMOUNT_TYPE='CR' AND REVERSAL='R' THEN -TRANS_FEE ELSE TRANS_FEE END) 
        ELSE 0 END THU_PHI_INTERCHANGE,
        
    CASE WHEN TRANS_TYPE='GDRTM' OR TRANS_TYPE='GDMSFF' THEN
            (CASE WHEN AMOUNT_TYPE='CR' AND REVERSAL='R' THEN -TRANS_FEE ELSE TRANS_FEE END) 
        ELSE 0 END PHI_INTERCHANGE_PHAI_TRA,
    
    CASE WHEN AMOUNT_TYPE = 'DR' OR (AMOUNT_TYPE='CR' AND REVERSAL='R') THEN 'BAO_NO' ELSE 'BAO_CO' END LOAI_HACH_TOAN,
    CASE WHEN TRANS_TYPE='GDTTHH' THEN 'A' 
        WHEN TRANS_TYPE='GDRTM' THEN 'B' 
        WHEN TRANS_TYPE='GDMSFF' THEN 'C' 
        WHEN TRANS_TYPE='GDNONFI' THEN 'D' 
        WHEN TRANS_TYPE='GDCB' THEN 'E' 
        WHEN TRANS_TYPE='FEECOLL' THEN 'E' END SEQ_NO
    FROM DSQT_HACH_TOAN
    WHERE NGAY_ADV=20200909 AND CURR='VND' AND CARD_BRN='MD' 
    --GROUP BY NGAY_ADV,CURR,CARD_BRN,AMOUNT_TYPE,TRANS_TYPE,REVERSAL
    order by TRANS_TYPE DESC
)
GROUP BY FILE_NAME,TRANS_TYPE,LOAI_HACH_TOAN,SEQ_NO
ORDER BY SEQ_NO,LOAI_HACH_TOAN DESC



